### ISSUE TITLE
"New session" doesn't work properly

### ISSUE THREAD

**Issue by lauramurgatroyd** [TomographicImaging/iDVC#28] opened 2021-06-07 14:56 UTC
We received feedback that the "New Session" button doesn't work properly - in version v20.07.6. Apparently you always have to close and re-open the app to create a new session.

We need to investigate exactly what the problem is

**Comment by paskino** [comment] 2021-11-10 12:07
Closing as we were not able to reproduce it.

**Closed by paskino** 2021-11-10 12:07 UTC
Labels: bug, investigate
